version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn jest --collectCoverage=true
      - store_artifacts:
          path: coverage
workflows:
  build-and-test:
    jobs:
      - build-and-test
